### ISSUE TITLE
Angular 5 support?

### ISSUE THREAD

**Issue by hkusulja** [ranveeraggarwal/ng2-adal-QuickStart#12]
Since now Angular 5 is latest, it seems that ngx-adal does not work with Angular 5 nice.
Can you check and fix?

**Comment by ranveeraggarwal** [comment]
There is a [PR on the library repo](https://github.com/sureshchahal/angular2-adal/pull/77/files) for enabling Angular 5 support. You'll probably have to wait until that is merged.

**Comment by hkusulja** [comment]
@ranveeraggarwal , yes, waiting about 2 months on this to be merged...

**Comment by ranveeraggarwal** [comment]
Ah, just saw that :/
Also, turns out the PR has a breaking change.

**Comment by dave0688** [comment]
Is there any new on this issue?

**Comment by kaburkett** [comment]
I found these for Angular 5:

https://github.com/jcmontx/angular5-adal-example

https://github.com/grumar/adal-angular5

**Comment by hkusulja** [comment]
This is now several years old, also you should use MSAL instead of ADAL library and Angular 5 is definitely old now beeing Angular 12 latest :P

So I am closing this and does not need attention anymore.
