### ISSUE TITLE
How to get Token as a string?

### ISSUE THREAD

**Issue by sudipta-chaudhari** [ranveeraggarwal/ng2-adal-QuickStart#3]
How can I fetch the Token as a string as I need to pass the Bearer token to authenticate & call a REST service.

**Comment by davidguerra** [comment]
Same problem! Help Please!!

**Comment by ranveeraggarwal** [comment]
I generally have a service that looks like:

    @Injectable()
    export class AuthService {

        constructor(private adalService: AdalService) {}

        public getToken(): Observable<string> {
            return this.adalService.acquireToken("https://xyz.onmicrosoft.com/abc").map(
                token => token.toString()
            );
        }
    }

**Comment by sudipta-chaudhari** [comment]
@ranveeraggarwal 

This is working only for Azure B2B AD and not for Azure B2C AD. I need to provide the B2C SignIn policy. (1) How can I make it work with B2C Azure AD?  
(2) How do I list the B2C Azure AD claims?

**Comment by ranveeraggarwal** [comment]
I am not sure how to do that. But according to this link, you might need to make graph calls to get claims: https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet

**Comment by bobby-ind** [comment]
B2C Authentication can be done using or without using GraphApi. I have done both Azure B2B and Azure B2C implementations in MVC/WebApi projects without using Graph Api. I don't want to use GraphApi for Angular 4.X projects also. If you come across an implementation of Azzure B2C without using Graph Api for Angular 4.X, please share. Thanks for your above reply on this. Cheers!
